"use client";

import { useEffect, useState } from "react";
import { BarChart3, Bell, ChevronDown, CircleDollarSign, LayoutDashboard, Package, Search, Settings, ShoppingCart, TrendingUp, Users } from "lucide-react";
import { useLanguage } from "@/components/LanguageProvider";
import ThemeToggle from "@/components/ThemeToggle";

type OrderRow = { id: string; customer: string; customerEn: string; status: string; statusEn: string; total: string; tone: string };

export default function DashboardPage() {
  const { lang, setLang } = useLanguage();
  const english = lang === "en";
  const toggleLanguage = () => setLang(english ? "ar" : "en");
  const [stats, setStats] = useState({ orders: "0", customers: "0", products: "0", sales: "0.00" });
  const [orders, setOrders] = useState<OrderRow[]>([]);
  const t = (ar: string, en: string) => english ? en : ar;

  useEffect(() => {
    fetch("/api/admin/overview").then(r => r.ok ? r.json() : Promise.reject()).then(data => setStats({ orders: Number(data.orders ?? 0).toLocaleString(english ? "en-US" : "ar-EG"), customers: Number(data.customers ?? 0).toLocaleString(english ? "en-US" : "ar-EG"), products: Number(data.products ?? 0).toLocaleString(english ? "en-US" : "ar-EG"), sales: Number(data.sales ?? 0).toLocaleString(english ? "en-US" : "ar-EG") })).catch(() => undefined);
    fetch("/api/admin/orders").then(r => r.ok ? r.json() : Promise.reject()).then(data => setOrders(Array.isArray(data) ? data : [])).catch(() => undefined);
  }, [english]);

  return <main className="min-h-screen bg-[#f5f7f8] text-slate-900 dark:bg-slate-950 dark:text-white">
    <aside className="fixed right-0 top-0 hidden h-screen w-64 border-l border-gray-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 lg:block"><div className="mb-12 flex items-center gap-2 text-xl font-black"><span className="grid h-10 w-10 place-items-center rounded-xl bg-green text-white">م</span> ملك ماركت</div><nav className="space-y-2 text-sm font-bold">
      <a className="flex items-center gap-3 rounded-xl bg-green px-4 py-3 text-white" href="#"><LayoutDashboard size={18}/>{t("نظرة عامة", "Overview")}</a><a className="flex items-center gap-3 rounded-xl px-4 py-3 text-slate-500 hover:bg-gray-50 dark:hover:bg-slate-800" href="#orders"><ShoppingCart size={18}/>{t("الطلبات", "Orders")} <span className="mr-auto rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-600">12</span></a><a className="flex items-center gap-3 rounded-xl px-4 py-3 text-slate-500 hover:bg-gray-50 dark:hover:bg-slate-800" href="#products"><Package size={18}/>{t("المنتجات", "Products")}</a><a className="flex items-center gap-3 rounded-xl px-4 py-3 text-slate-500 hover:bg-gray-50 dark:hover:bg-slate-800" href="#"><Users size={18}/>{t("العملاء", "Customers")}</a><a className="flex items-center gap-3 rounded-xl px-4 py-3 text-slate-500 hover:bg-gray-50 dark:hover:bg-slate-800" href="#"><BarChart3 size={18}/>{t("التقارير", "Reports")}</a><a className="mt-10 flex items-center gap-3 rounded-xl px-4 py-3 text-slate-500 hover:bg-gray-50 dark:hover:bg-slate-800" href="#"><Settings size={18}/>{t("الإعدادات", "Settings")}</a>
    </nav></aside>
    <section className="lg:mr-64"><header className="flex h-20 items-center justify-between border-b border-gray-200 bg-white px-5 sm:px-10 dark:border-slate-800 dark:bg-slate-900"><div><p className="text-sm text-slate-500">{t("الثلاثاء، 22 سبتمبر 2026", "Tuesday, September 22, 2026")}</p><h1 className="mt-1 text-xl font-black">{t("صباح الخير، مدير ملك ماركت 👋", "Good morning, Malek Market manager 👋")}</h1></div><div className="flex items-center gap-2"><button onClick={toggleLanguage} className="rounded-xl border border-gray-200 px-3 py-2 text-xs font-bold dark:border-slate-700" aria-label={t("تغيير اللغة", "Change language")}>{english ? "عربي" : "EN"}</button><ThemeToggle /><button className="rounded-xl border border-gray-200 p-2.5 text-slate-500 dark:border-slate-700" aria-label={t("الإشعارات", "Notifications")}><Bell size={19}/></button><div className="hidden items-center gap-2 rounded-xl border border-gray-200 p-2 dark:border-slate-700 sm:flex"><span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-100 font-bold text-green">م</span><span className="text-sm font-bold">{t("محمد المدير", "Mohamed Admin")}</span><ChevronDown size={15}/></div></div></header>
      <div className="p-5 sm:p-10"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-bold text-green">{t("لوحة التحكم", "Dashboard")}</p><h2 className="mt-1 text-3xl font-black">{t("نظرة عامة", "Overview")}</h2></div><div className="flex gap-2"><button className="flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-bold dark:border-slate-700 dark:bg-slate-900"><span>{t("آخر 30 يوم", "Last 30 days")}</span><ChevronDown size={15}/></button><button className="rounded-xl bg-green px-4 py-2.5 text-sm font-bold text-white">+ {t("إضافة منتج", "Add product")}</button></div></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<CircleDollarSign/>} label={t("إجمالي المبيعات", "Total sales")} value={`${stats.sales} ${t("ج.م", "EGP")}`} change="—"/><Stat icon={<ShoppingCart/>} label={t("إجمالي الطلبات", "Total orders")} value={stats.orders} change="—"/><Stat icon={<Users/>} label={t("العملاء", "Customers")} value={stats.customers} change="—"/><Stat icon={<Package/>} label={t("المنتجات", "Products")} value={stats.products} change="—"/></div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-3xl border border-gray-100 bg-white p-5 sm:p-7 dark:border-slate-800 dark:bg-slate-900"><div className="mb-8 flex items-center justify-between"><div><h3 className="font-black">{t("المبيعات خلال الشهر", "Monthly sales")}</h3><p className="mt-1 text-sm text-slate-500">{t("مقارنة بالأداء السابق", "Compared with previous performance")}</p></div><span className="flex items-center gap-1 text-sm font-bold text-green"><TrendingUp size={16}/> +18.4%</span></div><div className="flex h-56 items-end gap-2 sm:gap-4">{[38,52,45,66,58,72,62,78,68,90,81,96].map((h, i) => <div key={i} className="group flex flex-1 flex-col items-center gap-2"><div className={`w-full rounded-t-lg ${i === 11 ? "bg-green" : "bg-emerald-100 dark:bg-emerald-950"}`} style={{height: `${h}%`}}/><small className="text-[10px] text-slate-400">{(english ? ["May","Jun","Jul","Aug","Sep"] : ["مايو","يون","يول","أغس","سبت"])[i % 5]}</small></div>)}</div></div><div className="rounded-3xl border border-gray-100 bg-white p-5 sm:p-7 dark:border-slate-800 dark:bg-slate-900"><div className="mb-7 flex items-center justify-between"><h3 className="font-black">{t("الأكثر مبيعاً", "Best sellers")}</h3><button className="text-sm font-bold text-green">{t("عرض الكل", "View all")}</button></div><div className="space-y-5">{["فراولة طازجة", "زيت دوار الشمس", "لبن كامل الدسم", "أرز مصري فاخر"].map((name, i) => <div key={name} className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-sm font-black text-green">0{i + 1}</span><div className="flex-1"><b className="block text-sm">{english ? ["Fresh strawberries","Sunflower oil","Full-fat milk","Premium Egyptian rice"][i] : name}</b><small className="text-slate-500">{[342, 286, 218, 197][i]} {t("طلب", "orders")}</small></div><b className="text-sm">{["18,920", "14,680", "9,580", "8,740"][i]} ج.م</b></div>)}</div></div></div>
        <div id="orders" className="mt-6 rounded-3xl border border-gray-100 bg-white p-5 sm:p-7 dark:border-slate-800 dark:bg-slate-900"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h3 className="font-black">{t("آخر الطلبات", "Recent orders")}</h3><p className="mt-1 text-sm text-slate-500">{t("تابع حالة الطلبات الأخيرة", "Track the latest order status")}</p></div><div className="relative"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input placeholder={t("ابحث عن طلب...", "Search orders...")} className="rounded-xl border border-gray-200 py-2.5 pr-10 pl-3 text-sm outline-none focus:border-green dark:border-slate-700 dark:bg-slate-800"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-right text-sm"><thead className="border-b border-gray-100 text-slate-400 dark:border-slate-800"><tr>{[t("رقم الطلب", "Order"), t("العميل", "Customer"), t("الحالة", "Status"), t("الإجمالي", "Total"), t("الإجراء", "Action")].map(h => <th key={h} className="pb-4 font-medium">{h}</th>)}</tr></thead><tbody>{orders.length ? orders.map(o => <tr key={o.id} className="border-b border-gray-50 last:border-0 dark:border-slate-800"><td className="py-5 font-bold">{o.id}</td><td className="py-5">{english ? o.customerEn : o.customer}</td><td className="py-5"><span className={`rounded-lg px-3 py-1.5 text-xs font-bold ${o.tone}`}>{english ? o.statusEn : o.status}</span></td><td className="py-5 font-bold">{o.total}</td><td className="py-5"><button className="font-bold text-green">{t("التفاصيل", "Details")}</button></td></tr>) : <tr><td colSpan={5} className="py-12 text-center text-slate-400">{t("لا توجد طلبات بعد", "No orders yet")}</td></tr>}</tbody></table></div></div>
      </div></section>
  </main>;
}

function Stat({ icon, label, value, change }: { icon: React.ReactNode; label: string; value: string; change: string }) { return <div className="rounded-3xl border border-gray-100 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="mb-5 flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-50 text-green dark:bg-emerald-950">{icon}</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-green dark:bg-emerald-950">{change}</span></div><p className="text-sm text-slate-500">{label}</p><h3 className="mt-2 text-2xl font-black">{value}</h3></div>; }
